title: S3K0NDZ
iconURL: assets/default-icon.png
theme: jekyll-theme-slate

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: S3K0NDZ

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: G-Y4C63K721Q